{% set version = "1.6.0" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netCDF4/netCDF4-{{ version }}.tar.gz
  sha256: 95efa373d9a3e1cd0df7193e76e6680d9eca28e60097ca8139afea8a4346ba63

build:
  skip: true  # [not (win and vc>=14)]
  number: 0
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.19
    - cftime >=1.0.1
    - hdf5
    - libnetcdf
    - zlib
    - delocate  # [win]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cftime
    - hdf5
    - libnetcdf

test:
  imports:
    - netCDF4
    - cftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h

about:
  home: http://github.com/Unidata/netcdf4-python
  license: MIT
  license_file: LICENSE
  summary: Provides an object-oriented python interface to the netCDF version 4 library
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
