{% set version = "1.6.4" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/refs/tags/v{{ version }}rel.zip
  sha256: 45e52ec725d75faedd9d346f9a13bb28c85ecc845a3de2c9fd35713dc6189fbb

build:
  skip: true  # [not (win and vc>=14)]
  number: 0
  ignore_run_exports_from:
    - zlib
    - hdf5 1.14.0
    - libnetcdf 4.9.2
    - numpy

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.19
    - cftime >=1.0.1
    - hdf5 1.14.0
    - libnetcdf 4.9.2
    - zlib
    - delvewheel  # [win]
  run:
    - python

test:
  source_files:
    - test
  requires:
    - pip

about:
  home: http://github.com/Unidata/netcdf4-python
  license: MIT
  license_file: LICENSE
  summary: Provides an object-oriented python interface to the netCDF version 4 library
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
