{% set version = "1.6.1" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/refs/heads/v{{ version }}rel.tar.gz
  sha256: bc437e43325f54e6e679cd595f97611b39a02f5aaeb86e41fb63ca20220f5f4f

build:
  skip: true  # [not (win and vc>=14)]
  number: 0
  ignore_run_exports_from:
    - zlib
    - hdf5
    - libnetcdf
    - numpy

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.19
    - cftime >=1.0.1
    - hdf5
    - libnetcdf
    - zlib
    - delvewheel  # [win]
  run:
    - python

test:
  requires:
    - pip

about:
  home: http://github.com/Unidata/netcdf4-python
  license: MIT
  license_file: LICENSE
  summary: Provides an object-oriented python interface to the netCDF version 4 library
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
